"""
Perfusion module: drives the 0D coronary tree from the running simulation.

    P_AO  <- systemic circulation, circ.data['pressure_aorta']   (Eq. 23)
    P_IMP <- territory-averaged intramyocardial pressure         (Eq. 24)

Both enter the coronary tree as boundary conditions on the 0D circuit.  The
mechanics never see the coronary model, so nothing here can destabilise a
solve.  Flow feedback onto contractility (eta, Eqs. 19-20) comes later.

WHERE P_IMP COMES FROM
----------------------
Two sources, chosen in the JSON with "imp_source":

  "mesh"        the incompressibility Lagrange multiplier, volume-averaged
                over each coronary territory.  This is the real one.
  "prescribed"  a half-sine over systole with peaks from "imp_peak".  A
                placeholder, kept so the two can be compared directly.

The multiplier is the right field to use.  MyoFE enforces incompressibility
with a Lagrange multiplier rather than a penalty: forms.py carries
-p*(J - 1) in the strain energy, which puts -p*C^-1 in the PK2 and therefore
-p*I in the Cauchy stress.  So p IS the hydrostatic pressure of the tissue
surrounding each vessel, positive in compression, which is exactly what a
vessel embedded in contracting muscle has to push against.

Note this is deliberately NOT Eq. 17 of Wang et al., which averages the mean
normal stress tr(P F^T)/3J.  That quantity also picks up the trace of the
passive and active stress.  In an incompressible material the transverse
compression generated by active fibre tension already arrives through p, via
the incompressibility constraint, and p is a true hydrostatic pressure rather
than a stress invariant.  State this choice explicitly in any write-up.

WHY A VOLUME AVERAGE
--------------------
One terminal resistance stands in for many parallel microvascular beds, each
draining a small piece of tissue at its own local pressure:

    Q = sum_i (P_node - p_i)/R_i

Collapsing that to a single resistor Q = (P_node - Pbar)/Rt with
1/Rt = sum_i 1/R_i and solving for Pbar gives the conductance-weighted mean.
A larger piece of tissue holds proportionally more parallel vessels, so
1/R_i scales with volume and the weighted mean becomes

    Pbar = (1/V) * integral of p over the territory

So the volume average is not an approximation of convenience -- it is the
reduction that makes the lumped terminal reproduce the distributed bed.  It
assumes vessel density is uniform within a territory, which is worth stating.

The averaging is done with assemble() over a cell subdomain rather than by
hand over quadrature points, for two reasons: assemble weights each point by
its quadrature weight and Jacobian (an unweighted mean over Gauss points
over-represents small elements), and assemble performs the MPI reduction
internally.  Under MPI no single rank holds a whole territory.

UNITS
-----
Everything the coronary tree touches is mmHg.  The one exception is the
multiplier, which lives in the mechanics and is in Pa; PA_TO_MMHG converts it
at the boundary and nowhere else.

Python 2.7 compatible.
"""

import numpy as np

from .coronary_rc import CoronaryRC, SUBTREES


# The mechanics work in Pa.  Same factor circulation.py uses on the cavity
# pressure, which comes out of the same mixed function space.
PA_TO_MMHG = 0.0075

# MyoFE compiles forms with quadrature representation by default, for the
# Gauss-point myosim machinery.  Assembling these scalars without forcing
# uflacs can fail outright.  Same parameter LV_simulation.py passes on its
# myocardium_vol assembly -- keep them consistent.
FCP = {"representation": "uflacs"}


# Geometry of the AHA frame.  Measured offline in serial, because under MPI
# no rank sees both the apex and the base.  Overridable from JSON; these
# defaults are the values recorded in dependencies/aha_segmentation.py for
# the baseline mesh.  If the mesh changes, these must be re-measured.
DEFAULT_AHA = {
    "apex_point":  [0.0, 0.0, -0.7315],
    "axis_vector": [0.0, 0.0, 1.0],
    "axis_length": 0.7315,
    "c_ref":       [1.0, 0.0, 0.0],
    "lambda_c":    0.0902,
    "lambda_A":    0.3935,
    "lambda_M":    0.6967,
}


class perfusion(object):

    def __init__(self, perfusion_struct, parent, initial_pressure_arteries):

        self.parent = parent
        self.data = {}
        self.model = {}

        for k in perfusion_struct.keys():
            self.model[k] = perfusion_struct[k][0]

        self.terminal_resistance = self.model.get('terminal_resistance', None)

        subtree = self.model.get('subtree', 'lad_lcx_rca')
        if subtree not in SUBTREES:
            raise ValueError("unknown coronary subtree '%s'; options are %s"
                             % (subtree, sorted(SUBTREES.keys())))
        self.subtree = subtree

        self.imp_source = self.model.get('imp_source', 'prescribed')
        if self.imp_source not in ('mesh', 'prescribed'):
            raise ValueError("imp_source must be 'mesh' or 'prescribed', "
                             "got '%s'" % self.imp_source)

        self.aha_params = dict(DEFAULT_AHA)
        self.aha_params.update(self.model.get('aha', {}))

        # The protocol, and therefore the timestep, does not exist when
        # LV_simulation.__init__ runs.  A throwaway tree is built here only so
        # the territory names -- and hence the output column names -- are
        # known before create_data_structure runs.  The real one is built on
        # the first timestep.
        self.time_step = None
        self.tree = CoronaryRC(subtree, 1.0,
                               terminal_resistance=self.terminal_resistance)

        self.imp_peak_mmHg = self.model.get('imp_peak', {})
        for s in self.tree.terminals:
            if s not in self.imp_peak_mmHg:
                self.imp_peak_mmHg[s] = 70.0

        self.systole_fraction = self.model.get('systole_fraction', 0.4375)

        self.P = None
        self.initial_pressure_arteries = initial_pressure_arteries

        # territory marker, built lazily on the first mesh-sourced call
        self.dx = None
        self.territory_volume = None

        self.data['coronary_P_AO'] = initial_pressure_arteries
        for s in self.tree.terminals:
            self.data['coronary_flow_' + s] = 0.0
            self.data['coronary_imp_' + s] = 0.0

    # -----------------------------------------------------------------
    # setup
    # -----------------------------------------------------------------

    def build(self, time_step):
        """Factorize the coronary matrix for this timestep and set the initial
        state.  Deferred to the first timestep because the protocol, and so
        dt, does not exist at construction."""
        self.time_step = time_step
        self.tree = CoronaryRC(self.subtree, time_step,
                               terminal_resistance=self.terminal_resistance)
        self.P = self.tree.steady_state(self.initial_pressure_arteries,
                                        self.return_prescribed_imp(0.0))

    def build_territory_marker(self, mesh):
        """Tag every cell with the coronary terminal that supplies it, and
        record each territory's reference volume.

        Cell midpoints, not quadrature points: dx() integrates over cell
        subdomains, so the marker has to be per cell either way, and a
        midpoint is exact for a tetrahedron without assuming anything about
        quadrature ordering.  This matches the element-level convention used
        for material assignment -- a cell belongs to one territory, so no
        constitutive or boundary discontinuity ever falls inside an element.

        Purely local: each rank labels its own cells.  The only global
        operation is inside assemble(), which handles it.
        """
        from dolfin import MeshFunction, Cell, Measure, assemble, Constant

        try:
            from ..dependencies import aha_segmentation as aha
        except ImportError:
            import aha_segmentation as aha

        n_cells = mesh.num_cells()

        centroids = np.zeros((n_cells, 3))
        for i in range(n_cells):
            pt = Cell(mesh, i).midpoint()
            centroids[i, 0] = pt.x()
            centroids[i, 1] = pt.y()
            centroids[i, 2] = pt.z()

        lam, theta, n_clamped = aha.lambda_theta(centroids, self.aha_params)
        segment = aha.classify(lam, theta, self.aha_params)

        # A large clamp count means apex_point or axis_length is wrong, which
        # silently shifts every band boundary.  Cells legitimately sit a hair
        # outside [0,1] at the very apex and base, so a handful is expected.
        self.n_clamped = int(n_clamped)
        if n_clamped > 0.02 * max(n_cells, 1):
            print("perfusion: WARNING %d of %d cell centroids fell outside "
                  "lambda in [0,1]. Check apex_point and axis_length."
                  % (n_clamped, n_cells))

        # AHA segment -> terminal tag, via this configuration's territory map
        seg_to_tag = {}
        for j, term in enumerate(self.tree.terminals):
            for s in self.tree.regions[term]:
                seg_to_tag[s] = j + 1

        missing = [s for s in range(1, 18) if s not in seg_to_tag]
        if missing:
            raise RuntimeError("AHA segments %s are not assigned to any "
                               "terminal of '%s'" % (missing, self.subtree))

        marker = MeshFunction('size_t', mesh, mesh.topology().dim(), 0)
        marker_array = marker.array()
        for i in range(n_cells):
            marker_array[i] = seg_to_tag[segment[i]]

        self.marker = marker
        self.dx = Measure('dx', domain=mesh, subdomain_data=marker)

        # Reference volumes are constant -- dx is the reference measure -- so
        # they are assembled once here and only the numerator is assembled
        # per timestep.
        self.territory_volume = {}
        for j, term in enumerate(self.tree.terminals):
            vol = assemble(Constant(1.0) * self.dx(j + 1),
                           form_compiler_parameters=FCP)
            if vol <= 0.0:
                raise RuntimeError(
                    "territory '%s' (AHA %s) has zero volume: no cell centroid "
                    "landed in it. Check the AHA frame parameters."
                    % (term, self.tree.regions[term]))
            self.territory_volume[term] = vol

        total = sum(self.territory_volume.values())
        print("perfusion: territory volumes (reference configuration)")
        for term in self.tree.terminals:
            print("    %-6s %12.6f  %5.1f%%"
                  % (term, self.territory_volume[term],
                     100.0 * self.territory_volume[term] / total))

    # -----------------------------------------------------------------
    # intramyocardial pressure
    # -----------------------------------------------------------------

    def return_cycle_length(self):
        hr = self.parent.data['heart_rate']
        if hr <= 0.0:
            raise ValueError("heart rate must be positive to phase the "
                             "prescribed IMP waveform")
        return 60.0 / hr

    def return_prescribed_imp(self, t):
        """Placeholder: half-sine over systole, zero in diastole.  mmHg."""
        T = self.return_cycle_length()
        T_sys = self.systole_fraction * T
        phase = t - T * np.floor(t / T)
        if phase < T_sys:
            shape = np.sin(np.pi * phase / T_sys)
        else:
            shape = 0.0
        return dict((s, self.imp_peak_mmHg[s] * shape)
                    for s in self.tree.terminals)

    def return_computed_imp(self, p):
        """Volume-average the incompressibility multiplier over each coronary
        territory.  Returns mmHg keyed by terminal segment."""
        from dolfin import assemble

        out = {}
        for j, term in enumerate(self.tree.terminals):
            integral = assemble(p * self.dx(j + 1),
                                form_compiler_parameters=FCP)
            out[term] = PA_TO_MMHG * integral / self.territory_volume[term]
        return out

    # -----------------------------------------------------------------
    # time stepping
    # -----------------------------------------------------------------

    def implement_time_step(self, pressure_arteries, time_step, t,
                            mesh=None, p=None):
        """Advance the coronary tree one step.

        pressure_arteries is mmHg, straight from circ.data['pressure_aorta'],
        and is used as-is: the tree runs in the same units.

        mesh and p are the simulation mesh and the incompressibility
        multiplier.  They are required when imp_source is 'mesh', and ignored
        otherwise.  Call this AFTER the mechanics solve, or p will be one
        timestep stale.
        """
        if self.time_step is None:
            self.build(time_step)
        elif abs(time_step - self.time_step) > 1e-12:
            raise ValueError(
                "coronary matrix was factorized for dt=%g but the simulation "
                "is stepping at dt=%g; rebuild the tree if dt changes"
                % (self.time_step, time_step))

        if self.imp_source == 'mesh':
            if mesh is None or p is None:
                raise ValueError(
                    "imp_source is 'mesh' but implement_time_step was called "
                    "without mesh and p")
            if self.dx is None:
                self.build_territory_marker(mesh)
            P_IMP = self.return_computed_imp(p)
        else:
            P_IMP = self.return_prescribed_imp(t)

        self.P = self.tree.step(self.P, pressure_arteries, P_IMP)

        q = self.tree.perfusion(self.P, pressure_arteries, P_IMP)

        self.data['coronary_P_AO'] = pressure_arteries
        for s in self.tree.terminals:
            self.data['coronary_flow_' + s] = q[s]
            self.data['coronary_imp_' + s] = P_IMP[s]

        return q
